version: '2'
services:
    helpop-app:
        image: helpop
        external_links:
            - helpop-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/helpop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    helpop-mysql:
        extends:
            file: mysql.yml
            service: helpop-mysql
